plugins {
    alias libs.plugins.android.application
    alias libs.plugins.hilt.android
    alias libs.plugins.ksp
    alias libs.plugins.oss.licenses
    alias libs.plugins.secrets
    alias libs.plugins.google.services
    alias libs.plugins.firebase.crashlytics
}

android {
    compileSdk 37
    compileSdkMinor 0

    defaultConfig {
        applicationId 'com.puntogris.smartwear'
        minSdk 24
        targetSdk 37
        versionCode 16
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig = true
        viewBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace 'com.puntogris.smartwear'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.legacy.support

    //Testing
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core

    //Material Design
    implementation libs.google.material

    //Firebase
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics.ktx
    implementation libs.firebase.crashlytics

    // Navigation
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx

    //Preferences
    implementation libs.androidx.preference.ktx

    //Activities ktx
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx

    //Google location
    implementation libs.play.services.location
    implementation libs.play.services.plus

    //Coroutines
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.play.services

    //ViewModel ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx

    //Lifecycle
    implementation libs.androidx.lifecycle.common.java8
    implementation libs.androidx.lifecycle.process
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.livedata.ktx

    //Lottie
    implementation libs.lottie

    //Hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    //Room
    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler

    //Open source licenses
    implementation libs.play.services.oss.licenses

    //Retrofit
    implementation libs.retrofit.runtime
    implementation libs.retrofit.converter.gson
    implementation libs.okhttp.logging.interceptor

    //Glide
    implementation libs.glide.runtime
    annotationProcessor libs.glide.compiler

    //Tab layout dots indicators
    implementation libs.dots.indicator

    //Date and time
    implementation libs.threetenabp
}
